### ISSUE TITLE
Trigger löst nicht aus

### ISSUE THREAD

**Issue by ozwo71** [der8en/Fritz-Call-Monitor-Feed#1]
Hallo, vielen Dank für diese coole Automation - kommt mir sehr gelegen, da ich gerade mein Dashboard umbaue.

Leider funktioniert Dein Code bei mir nicht vollständig:
Die Historie für einen ausgehenden Anruf im Fritzbox-Callmonitor zeigt eindeutig idle->dialing->talking->idle
![grafik](https://github.com/der8en/Fritz-Call-Monitor-Feed/assets/46357623/1c42f29f-3fbc-4ff0-9565-52e4e8748dc7)

Der Trace für die Automation sagt aber, dass der Step nicht ausgeführt wurde:
![grafik](https://github.com/der8en/Fritz-Call-Monitor-Feed/assets/46357623/824c41eb-d30f-4731-88b9-cbcfe834742f)

Dementsprechend landet der Anruf nicht im Helper "...feed".
Das "Feed bereinigen" am Ende wurde aber sehr wohl ausgeführt - also wurde der erneute Wechsel auf idle erkannt.

Hast Du eine Idee, woran das liegen könnte?
Danke und Grüße

**Comment by der8en** [comment]
Hallo,
Ist das bei jedem ausgehendem Anruf oder nur ab und zu?
Bitte geh mal bei Traces mit dem Peil neben dem Datum nach links, denn dieser Schnitt ist ein eigener Trace.

PS: Ich bin diese Woche unterwegs und schaue es mir dann nochmal genauer an
Viele Grüße

**Comment by der8en** [comment]
Hallo,
ist das bei jedem ausgehendem Anruf so, oder nur ab und zu?
Bitte geh mal bei Traces mit dem Pfeil 1-2 Schritte weiter nach links, denn der Schritt ist ein eigener Trace.

PS: Ich bin diese Woche noch unterwegs und schau es mir nächste Woche genauer an.
Viele Grüße

**Comment by ozwo71** [comment]
Hallo,
ich habe den Fehler selbst gemacht (und auch gefunden...). Wenn man ins HA Log schaut, sieht man es auch sofort:
![grafik](https://github.com/der8en/Fritz-Call-Monitor-Feed/assets/46357623/b3c5c560-21b7-4059-8ff0-e823b545455d)

Der Helper war nicht lang genug - hatte ich für den "Anrufer" korrekt gesetzt, aber nicht für den Feed. Und weil manche Einträge mit 100 Zeichen kommen, hat es halt manchmal funktioniert...und manchmal nicht.
Danke für die coole Automation und viele Grüße
