### ISSUE TITLE
Fehlende Namensauflösung bei Nummernwahl ohne Vorwahl

### ISSUE THREAD

**Issue by joder79** [der8en/Fritz-Call-Monitor-Feed#2]
Die Namensauflösung in der Automatisierung klappt seit Hinterlegung des Präfix "+49" unter "Konfigurieren" in der "AVM Fritz!Box Call Monitor"-Integration, wie sie sollte. Ich fände es hilfreich, diesen nötigen Schritt in die umseitige (und sonst tiptop nachvollziehbare!) Anleitung mit aufzunehmen.

Wenn man nun innerhalb des selben Vorwahlbereichs eine Telefonnummer ohne Vorwahl eingibt, so gibt es keine Namensauflösung.

Bsp.:
Für +49 1234 - 666 666 ist Max Mustermann hinterlegt. Bei Auswahl des Namens im Telefonbuch oder manueller Eingabe der kompletten Telefonnummer 01234-666666 wird M.M. auch angezeigt.
Gibt man nun, weil man sich eben innerhalb des selben 01234-Vorwahlbereichs befindet, nur schnell 666666 ein anstatt den Telefonbucheintrag auszuwählen, so listet die Automatisierung auch nur die Ziffernfolge ab, eine Namenszuordnung findet nicht mehr statt.

Gibt es eine Möglichkeit, die Namenszuordnung auch in solchen Fällen durchführen zu lassen? Durch Präfix-Anpassung (man kann verschiedene Präfixe - getrennt durch ";" - eingeben)? Durch Anpassung des YAML-Codes? ...?

Danke für alle Bemühungen!

**Comment by der8en** [comment]
Hallo,
diese Frage bitte direkt an den Entwickler der AVM FRITZ!Box Call Monitor Integration richten. Die Automatisierung kann daran leider nichts ändern.
