### ISSUE TITLE
Feed-Einträge temporär unsichtbar

### ISSUE THREAD

**Issue by joder79** [der8en/Fritz-Call-Monitor-Feed#4]
Zu guter Letzt noch ein mir unerklärliches Problem in der Hoffnung auf Lösung - nicht, bevor ich mich einmal explizit für dieses super Angebot bedanke; ganz großes Dankeschön, wirklich!

Es kommt immer wieder vor, dass vom Feed nur noch die Zeitangabe gelistet wird, der Rest wird unsichtbar - siehe Screenshot:
![Screenshot_20240530-130131](https://github.com/der8en/Fritz-Call-Monitor-Feed/assets/58642811/a3f09147-6bf1-4da0-a52f-98e23d075f65)

Klicke ich dann einen unsichtbaren Eintrag ein, wird mir für gewöhnlich eine Fehlermeldung angezeigt - siehe Screenshot:
![Screenshot_20240530-130150](https://github.com/der8en/Fritz-Call-Monitor-Feed/assets/58642811/4cd74b3d-fdbb-4d38-8590-48f1e85b04bb)

Und das "Beste" dabei - an diesem Punkt reicht es schon, dass ich einfach "abbreche" und zurück zum Dachboard gehe: Schon ist nämlich alles wieder so, wie es sein sollte - siehe Screenshot:
![Screenshot_20240530-130150](https://github.com/der8en/Fritz-Call-Monitor-Feed/assets/58642811/decc8ea8-ce79-4250-9e16-5290679d34b4)

Ich tippe auf irgendein Caching-Problem?!

**Comment by der8en** [comment]
Das Problem hab ich hin und wieder auch, aber das liegt an der Lovelace Home Feed Card. Bitte die Frage dorthin schicken.
